// <auto-generated />
using System;
using DotBlog.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotBlog.Server.Migrations
{
    [DbContext(typeof(DotBlogDbContext))]
    partial class DotBlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("DotBlog.Server.Entities.Article", b =>
                {
                    b.Property<uint>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShown")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Like")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PostTime")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1u,
                            Alias = "Hello-World",
                            Author = "DotBlog",
                            Content = "欢迎使用，这是DotBlog自动生成的第一篇文章",
                            Description = "自动生成的第一篇文章",
                            IsShown = true,
                            Like = 0u,
                            PostTime = new DateTime(2021, 2, 26, 16, 42, 1, 950, DateTimeKind.Local).AddTicks(3885),
                            Read = 0u,
                            Title = "HelloWorld"
                        });
                });

            modelBuilder.Entity("DotBlog.Server.Entities.Reply", b =>
                {
                    b.Property<uint>("ReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Like")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReplyTime")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReplyTo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserExplore")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPlatform")
                        .HasColumnType("TEXT");

                    b.HasKey("ReplyId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ReplyId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("DotBlog.Server.Entities.Reply", b =>
                {
                    b.HasOne("DotBlog.Server.Entities.Article", "Article")
                        .WithMany("Replies")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("DotBlog.Server.Entities.Article", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
